# Team vs Team system settings

queue:
  max-players: 500 # Maximum number of players in the queue

teams:
  default-colors:
    - RED
    - BLUE
    - GREEN
    - YELLOW
    - DARK_RED
    - DARK_GRAY
  default-names:
    - "Alpha"
    - "Bravo"
    - "Charlie"
    - "Delta"
    - "Echo"
    - "Foxtrot"

match:
  auto-assign: true # Automatic player allocation
  balance-teams: true # Balancing teams by number
  min-players-per-team: 1 # Minimum number of players per team

messages:
  join-success: "You have successfully joined the queue for Team vs Team!"
  already-in-queue: "You are now in the queue!"
  match-started: "The distribution of players has begun! We wish you success!"
  not-enough-players: "There are not enough players to create a match."
  team-assigned: "You are on the team {team_name} with color {team_color}."
